name: Check Droid Deals

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  check-deal:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Deal and Notify
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: "🚨 **New Droid Deal Alert!** 🚨\n```json\n$(curl -s [https://gonk.tools/api/droid-alerts/limited-deal](https://gonk.tools/api/droid-alerts/limited-deal))\n```"
          
